<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseBibEquipement extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('patbati.bib_equipement');
        $this->hasColumn('codeequipement', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('equipement', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('codetypeequip', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
    $this->hasOne('BibTypeEquipement', array(
             'local' => 'codetypeequip',
             'foreign' => 'codetypeequip'));

        $this->hasMany('Equipements as Equipementss', array(
             'local' => 'codeequipement',
             'foreign' => 'codeequipement'));
    }
}