<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseSecondOeuvre extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('patbati.second_oeuvre');
        $this->hasColumn('indexso', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('indexbatiment', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'notnull' => true,
             ));
        $this->hasColumn('codeso', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'notnull' => true,
             ));
        $this->hasColumn('codeconservation', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'notnull' => true,
             ));
        $this->hasColumn('info_so', 'string', 1000, array(
             'type' => 'string',
             'length' => 1000,
             ));
        $this->hasColumn('so_rem', 'boolean', null, array(
             'type' => 'boolean',
             ));
    }

    public function setUp()
    {
        parent::setUp();
    $this->hasOne('Identification', array(
             'local' => 'indexbatiment',
             'foreign' => 'indexbatiment'));

        $this->hasOne('BibSo', array(
             'local' => 'codeso',
             'foreign' => 'codeso'));

        $this->hasOne('BibConservation', array(
             'local' => 'codeconservation',
             'foreign' => 'codeconservation'));

        $this->hasMany('BibMateriauxFins as RelSoMatfinss', array(
             'refClass' => 'RelSoMatfins',
             'local' => 'indexso',
             'foreign' => 'codematfins'));
    }
}