<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseRelIdentPerspective extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('patbati.rel_ident_perspective');
        $this->hasColumn('indexbatiment', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'primary' => true,
             ));
        $this->hasColumn('codeperspective', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
    $this->hasOne('Identification', array(
             'local' => 'indexbatiment',
             'foreign' => 'indexbatiment'));

        $this->hasOne('BibFinition', array(
             'local' => 'codeperspective',
             'foreign' => 'codeperspective'));
    }
}