<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseBibCommune extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('patbati.bib_commune');
        $this->hasColumn('codeinsee', 'string', 1, array(
             'type' => 'string',
             'length' => 1,
             'primary' => true,
             ));
        $this->hasColumn('codecanton', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'notnull' => true,
             ));
        $this->hasColumn('codesecteur', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'notnull' => true,
             ));
        $this->hasColumn('commune', 'string', 30, array(
             'type' => 'string',
             'length' => 30,
             ));
    }

    public function setUp()
    {
        parent::setUp();
    $this->hasOne('BibCanton', array(
             'local' => 'codecanton',
             'foreign' => 'codecanton'));

        $this->hasOne('BibSecteur', array(
             'local' => 'codesecteur',
             'foreign' => 'codesecteur'));

        $this->hasMany('Identification as Identifications', array(
             'local' => 'codeinsee',
             'foreign' => 'codeinsee'));
    }
}