<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseBibNature extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('patbati.bib_nature');
        $this->hasColumn('codenature', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('nature', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
    $this->hasMany('RelRecommande as RelRecommandes', array(
             'local' => 'codenature',
             'foreign' => 'codenature'));

        $this->hasMany('Travaux as Travauxs', array(
             'local' => 'codenature',
             'foreign' => 'codenature'));
    }
}