<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseRelRemplace extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('patbati.rel_remplace');
        $this->hasColumn('indexstructure_ancien', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'primary' => true,
             ));
        $this->hasColumn('indexstructure_nouveau', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
    $this->hasOne('Structures as StructuresAncien', array(
             'local' => 'indexstructure_ancien',
             'foreign' => 'indexstructure'));

        $this->hasOne('Structures as StructuresNouveau', array(
             'local' => 'indexstructure_nouveau',
             'foreign' => 'indexstructure'));
    }
}