<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseBibSecteur extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('patbati.bib_secteur');
        $this->hasColumn('codesecteur', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('secteur', 'string', 12, array(
             'type' => 'string',
             'length' => 12,
             ));
    }

    public function setUp()
    {
        parent::setUp();
    $this->hasMany('BibCommune as BibCommunes', array(
             'local' => 'codesecteur',
             'foreign' => 'codesecteur'));
    }
}