<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseBibPerspective extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('patbati.bib_perspective');
        $this->hasColumn('codeperspective', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('perspective', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
    $this->hasMany('Identification as RelIdentPerspectives', array(
             'refClass' => 'RelIdentPerspective',
             'local' => 'codeperspective',
             'foreign' => 'indexbatiment'));
    }
}