<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseUserCredential extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('user_credential');
        $this->hasColumn('user_id', 'integer', 4, array('type' => 'integer', 'length' => 4, 'primary' => true));
        $this->hasColumn('credentials', 'string', 255, array('type' => 'string', 'length' => 255, 'notnull' => true));
    }

}