<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseBibExposition extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('patbati.bib_exposition');
        $this->hasColumn('indexexposition', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('nomexposition', 'string', 2, array(
             'type' => 'string',
             'length' => 2,
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
    $this->hasMany('Identification as Identifications', array(
             'local' => 'indexexposition',
             'foreign' => 'exposition'));
    }
}