<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseTravaux extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('patbati.travaux');
        $this->hasColumn('indextravaux', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('codeusage', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'notnull' => true,
             ));
        $this->hasColumn('codenature', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'notnull' => true,
             ));
        $this->hasColumn('indexdemande', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'notnull' => true,
             ));
        $this->hasColumn('date_travaux', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('autorisation', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('subvention_pne', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
    $this->hasOne('BibUsage', array(
             'local' => 'codeusage',
             'foreign' => 'codeusage'));

        $this->hasOne('BibNature', array(
             'local' => 'codenature',
             'foreign' => 'codenature'));

        $this->hasOne('Demande', array(
             'local' => 'indexdemande',
             'foreign' => 'indexdemande'));
    }
}