<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseRelMatgeMeo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('patbati.rel_matge_meo');
        $this->hasColumn('codematge', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'primary' => true,
             ));
        $this->hasColumn('codemeo', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
    $this->hasOne('BibMateriauxGe', array(
             'local' => 'codematge',
             'foreign' => 'codematge'));

        $this->hasOne('BibMeoeuvre', array(
             'local' => 'codemeo',
             'foreign' => 'codemeo'));
    }
}