<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseElementsPaysagers extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('patbati.elements_paysagers');
        $this->hasColumn('indexep', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('codeep', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'notnull' => true,
             ));
        $this->hasColumn('codeconservation', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'notnull' => true,
             ));
        $this->hasColumn('indexbatiment', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'notnull' => true,
             ));
        $this->hasColumn('info_ep', 'string', 200, array(
             'type' => 'string',
             'length' => 200,
             ));
        $this->hasColumn('ep_rem', 'boolean', null, array(
             'type' => 'boolean',
             ));
    }

    public function setUp()
    {
        parent::setUp();
    $this->hasOne('BibElementPaysager', array(
             'local' => 'codeep',
             'foreign' => 'codeep'));

        $this->hasOne('BibConservation', array(
             'local' => 'codeconservation',
             'foreign' => 'codeconservation'));

        $this->hasOne('Identification', array(
             'local' => 'indexbatiment',
             'foreign' => 'indexbatiment'));
    }
}