<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseCorRoles extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('utilisateurs.cor_roles');
        $this->hasColumn('id_role_groupe', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'notnull' => true,
             ));
        $this->hasColumn('id_role_utilisateur', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'notnull' => true,
             ));
    }

}