<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseBibConservation extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('patbati.bib_conservation');
        $this->hasColumn('codeconservation', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('conservation', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
    $this->hasMany('ElementsPaysagers as ElementsPaysagerss', array(
             'local' => 'codeconservation',
             'foreign' => 'codeconservation'));

        $this->hasMany('Equipements as Equipementss', array(
             'local' => 'codeconservation',
             'foreign' => 'codeconservation'));

        $this->hasMany('Identification as Identifications', array(
             'local' => 'codeconservation',
             'foreign' => 'codeconservation'));

        $this->hasMany('SecondOeuvre as SecondOeuvres', array(
             'local' => 'codeconservation',
             'foreign' => 'codeconservation'));

        $this->hasMany('Structures as Structuress', array(
             'local' => 'codeconservation',
             'foreign' => 'codeconservation'));
    }
}