<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseBibNotepatri extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('patbati.bib_notepatri');
        $this->hasColumn('indexnotepatri', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('valnotepatri', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
    $this->hasMany('Identification as Identifications', array(
             'local' => 'indexnotepatri',
             'foreign' => 'notepatri'));
    }
}