<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseRelMatfinsFinition extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('patbati.rel_matfins_finition');
        $this->hasColumn('codematfins', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'primary' => true,
             ));
        $this->hasColumn('codefinition', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
    $this->hasOne('BibMateriauxFins', array(
             'local' => 'codematfins',
             'foreign' => 'codematfins'));

        $this->hasOne('BibFinition', array(
             'local' => 'codefinition',
             'foreign' => 'codefinition'));
    }
}