<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseDemande extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('patbati.demande');
        $this->hasColumn('indexdemande', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('indexbatiment', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'notnull' => true,
             ));
        $this->hasColumn('demandep', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('autorisationp', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('date_permis', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('num_permis', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('date_demandep', 'date', null, array(
             'type' => 'date',
             ));
    }

    public function setUp()
    {
        parent::setUp();
    $this->hasOne('Identification', array(
             'local' => 'indexbatiment',
             'foreign' => 'indexbatiment'));

        $this->hasMany('Travaux as Travauxs', array(
             'local' => 'indexdemande',
             'foreign' => 'indexdemande'));
    }
}