<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseBibSo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('patbati.bib_so');
        $this->hasColumn('codeso', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('second_oeuvre', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('codetypeso', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
    $this->hasOne('BibTypeSo', array(
             'local' => 'codetypeso',
             'foreign' => 'codetypeso'));

        $this->hasMany('SecondOeuvre as SecondOeuvres', array(
             'local' => 'codeso',
             'foreign' => 'codeso'));
    }
}