<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseBibPersonnes extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('patbati.bib_personnes');
        $this->hasColumn('codepersonne', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('personne', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             'notnull' => true,
             ));
        $this->hasColumn('descriptif', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
    $this->hasMany('Enquetes as Enquetess', array(
             'local' => 'codepersonne',
             'foreign' => 'codepersonne'));

        $this->hasMany('Illustration as Illustrations', array(
             'local' => 'codepersonne',
             'foreign' => 'codepersonne'));
    }
}