<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseEquipements extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('patbati.equipements');
        $this->hasColumn('indexequipement', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('codeequipement', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'notnull' => true,
             ));
        $this->hasColumn('codeconservation', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'notnull' => true,
             ));
        $this->hasColumn('indexbatiment', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'notnull' => true,
             ));
        $this->hasColumn('info_equip', 'string', 200, array(
             'type' => 'string',
             'length' => 200,
             ));
        $this->hasColumn('equipement_rem', 'boolean', null, array(
             'type' => 'boolean',
             ));
    }

    public function setUp()
    {
        parent::setUp();
    $this->hasOne('BibEquipement', array(
             'local' => 'codeequipement',
             'foreign' => 'codeequipement'));

        $this->hasOne('BibConservation', array(
             'local' => 'codeconservation',
             'foreign' => 'codeconservation'));

        $this->hasOne('Identification', array(
             'local' => 'indexbatiment',
             'foreign' => 'indexbatiment'));
    }
}