<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseRelProtection extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('patbati.rel_protection');
        $this->hasColumn('indexbatiment', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'primary' => true,
             ));
        $this->hasColumn('codeprotection', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
    $this->hasOne('Identification', array(
             'local' => 'indexbatiment',
             'foreign' => 'indexbatiment',
             'onDelete' => 'cascade'));

        $this->hasOne('BibProtection', array(
             'local' => 'codeprotection',
             'foreign' => 'codeprotection'));
    }
}