<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseBibProtection extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('patbati.bib_protection');
        $this->hasColumn('codeprotection', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('protection', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
    $this->hasMany('Identification as RelProtections', array(
             'refClass' => 'RelProtection',
             'local' => 'codeprotection',
             'foreign' => 'indexbatiment'));
    }
}