<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseBibMeoeuvre extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('patbati.bib_meoeuvre');
        $this->hasColumn('codemeo', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('meoeuvre', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
    $this->hasMany('BibMateriauxGe as RelMatgeMeos', array(
             'refClass' => 'RelMatgeMeo',
             'local' => 'codemeo',
             'foreign' => 'codematge'));

        $this->hasMany('Structures as Structuress', array(
             'local' => 'codemeo',
             'foreign' => 'codemeo'));
    }
}