<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseBibElementPaysager extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('patbati.bib_element_paysager');
        $this->hasColumn('codeep', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('naturels_construits', 'string', 1, array(
             'type' => 'string',
             'length' => 1,
             ));
        $this->hasColumn('elements_paysagers', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
    $this->hasMany('ElementsPaysagers as ElementsPaysagerss', array(
             'local' => 'codeep',
             'foreign' => 'codeep'));
    }
}