<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseBibClasseArchi extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('patbati.bib_classe_archi');
        $this->hasColumn('codeclasse', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('classe', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('classe_decrite', 'string', 200, array(
             'type' => 'string',
             'length' => 200,
             ));
    }

    public function setUp()
    {
        parent::setUp();
    $this->hasMany('Identification as Identifications', array(
             'local' => 'codeclasse',
             'foreign' => 'codeclasse'));

        $this->hasMany('RelRecommande as RelRecommandes', array(
             'local' => 'codeclasse',
             'foreign' => 'codeclasse'));
    }
}