<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseEnquetes extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('patbati.enquetes');
        $this->hasColumn('indexenquete', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('codepersonne', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'notnull' => true,
             ));
        $this->hasColumn('indexbatiment', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'notnull' => true,
             ));
        $this->hasColumn('date_enquete', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('date_redaction', 'date', null, array(
             'type' => 'date',
             ));
    }

    public function setUp()
    {
        parent::setUp();
    $this->hasOne('BibPersonnes', array(
             'local' => 'codepersonne',
             'foreign' => 'codepersonne'));

        $this->hasOne('Identification', array(
             'local' => 'indexbatiment',
             'foreign' => 'indexbatiment'));
    }
}