<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseBibFinition extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('patbati.bib_finition');
        $this->hasColumn('codefinition', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('finition', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
    $this->hasMany('BibMateriauxFins as RelMatfinsFinitions', array(
             'refClass' => 'RelMatfinsFinition',
             'local' => 'codefinition',
             'foreign' => 'codematfins'));

        $this->hasMany('RelIdentPerspective as RelIdentPerspectives', array(
             'local' => 'codeperspective',
             'foreign' => 'codeperspective'));

        $this->hasMany('RelSoMatfins as RelSoMatfinss', array(
             'local' => 'codefinition',
             'foreign' => 'codefinition'));

        $this->hasMany('RelStructuresMatfins as RelStructuresMatfinss', array(
             'local' => 'codefinition',
             'foreign' => 'codefinition'));
    }
}