<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseRelRecommande extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('patbati.rel_recommande');
        $this->hasColumn('codeclasse', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'primary' => true,
             ));
        $this->hasColumn('codenature', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
    $this->hasOne('BibClasseArchi', array(
             'local' => 'codeclasse',
             'foreign' => 'codeclasse'));

        $this->hasOne('BibNature', array(
             'local' => 'codenature',
             'foreign' => 'codenature'));
    }
}