<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BibConservation extends BaseBibConservation
{
	public function __toString() {
		return $this->getConservation();
	}
}