<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BibEquipement extends BaseBibEquipement
{
	public function __toString() {
		return $this->getEquipement();
	}
}