<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BibElementPaysager extends BaseBibElementPaysager
{
	public function __toString() {
		return $this->getElementsPaysagers();
	}
}