<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BibExposition extends BaseBibExposition
{
	public function __toString() {
		return $this->getNomExposition();
	}
}