<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BibFinition extends BaseBibFinition
{
	public function __toString() 
	{
		return $this->getFinition();
	}
	
	public function getLinkedCodematfins()
	{
		$codeMatfins = array();
		
		foreach ($this->getRelMatfinsFinitions() as $relMatfinsFinition)
		{
			$codeMatfins[] = $relMatfinsFinition->getCodematfins();
		}
		
		return $codeMatfins;
	}
}