<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BibIllustration extends BaseBibIllustration
{
	public function __toString() {
		return $this->getIllustration();
	}
}