<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BibMateriauxFins extends BaseBibMateriauxFins
{
	public function __toString() 
	{
		return $this->getMatfins();
	}
}