<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BibMeoeuvre extends BaseBibMeoeuvre
{
	public function __toString()
	{
		return $this->getMeoeuvre();
	}
	
	public function getLinkedCodematges()
	{
		$codeMatges = array();
		
		foreach ($this->getRelMatgeMeos() as $relMatgeMeo)
		{
			$codeMatges[] = $relMatgeMeo->getCodematge();
		}
		
		return $codeMatges;
	}
}