<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BibNotepatri extends BaseBibNotepatri
{
	public function __toString() {
		return $this->getValNotepatri();
	}
}