<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BibProtection extends BaseBibProtection
{
	public function __toString() {
		return $this->getProtection();
	}
}