<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BibPerspective extends BaseBibPerspective
{
	public function __toString()
	{
		return $this->getPerspective();
	}
}