<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BibTypeEquipement extends BaseBibTypeEquipement
{
	public function __toString()
	{
		return $this->getTypeEquip();
	}
}