<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Equipements extends BaseEquipements
{
	public function getNomequipement()
	{
		return $this->getBibEquipement()->getEquipement();
	}
	
	public function getCodetypeequip()
	{
		return $this->getBibEquipement()->getBibTypeEquipement()->getCodetypeequip();
	}
}