<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Identification extends BaseIdentification
{
	public function __toString()
	{
		return $this->getAppelation();
	}

	public function getLinkFiche()
	{
		return $this->getIndexbatiment();
	}

	public function getLinkFicheSummary()
	{
		return $this->getIndexbatiment();
	}

	public function getPrincipalIllustration()
	{
		$q = Doctrine_Query::create()
			->select('ill.*')
		    ->from('Illustration ill')
		    ->innerJoin('ill.Identification ide')
		    ->innerJoin('ill.BibIllustration bibill')
		    ->where('ide.indexbatiment = ?', $this->getPrimaryKey())
		    ->andWhere('bibill.codeillustration = ?', 6);

		return $q->fetchOne();
	}

	public function getIllustrationByType($type)
	{
		$q = Doctrine_Query::create()
			->select('ill.*')
		    ->from('Illustration ill')
		    ->innerJoin('ill.Identification ide')
		    ->innerJoin('ill.BibIllustration bibill')
		    ->where('ide.indexbatiment = ?', $this->getPrimaryKey())
		    ->andWhere('bibill.codeillustration = ?', $type);

		return $q->fetchOne();
	}

	public function getSecteurCommune()
	{
		return $this->getBibCommune()->getBibSecteur()->getSecteur();
	}

	public function getCountTravaux()
	{
		$q = Doctrine_Query::create()
			->select('COUNT(t.indextravaux) as count')
		    ->from('Travaux t')
		    ->leftJoin('t.Demande d')
		    ->where('d.indexbatiment = ? ', $this->getPrimaryKey());

		 return $q->fetchOne()->count;
	}

	public function getTravaux()
	{
		$q = Doctrine_Query::create()
			->select('t.*')
		    ->from('Travaux t')
		    ->leftJoin('t.Demande d')
		    ->where('d.indexbatiment = ? ', $this->getPrimaryKey());

		 return $q->execute();
	}

	public function getLastDateTravaux()
	{
		$q = Doctrine_Query::create()
			->select('t.date_travaux')
		    ->from('Travaux t')
		    ->leftJoin('t.Demande d')
		    ->where('d.indexbatiment = ? ', $this->getPrimaryKey())
			->orderby('t.date_travaux DESC');
		 return $q->fetchOne();
	}


/* id des structures dans la db
"1";"Terre plein"
"2";"Structure porteuse verticale"
"3";"Structure porteuse horizontale"
"4";"Charpente"
"5";"Couverture"
"6";"Balcon"
"7";"Escalier"
"8";"Galerie"
 */
	public function getStructureHorizontalePorteuse()
	{
		return $this->getStructureByCode(3);
	}
	
    public function getStructureVerticalePorteuse()
	{
		return $this->getStructureByCode(2);
	}

	public function getStructureCharpente()
	{
		return $this->getStructureByCode(4);
	}

	public function getStructureCouverture()
	{
		return $this->getStructureByCode(5);
	}

	protected function getStructureByCode($codeStructure)
	{
		$q = Doctrine_Query::create()
		    ->from('Structures s')
		    ->leftJoin('s.Identification ide')
		    ->where('ide.indexbatiment = ? ', $this->getPrimaryKey())
		    ->addWhere('s.codestructure = ?', $codeStructure);

		 return $q->execute();
	}

	public function getStructuress()
	{
		$q = Doctrine_Query::create()
		    ->from('Structures s')
		    ->leftJoin('s.BibConservation bc')
		    ->leftJoin('s.BibMateriauxGe bm')
		    ->leftJoin('bm.RelMatgeMeos rmm')
		    ->leftJoin('s.BibStructure bs')
		    ->leftJoin('s.BibMeoeuvre bme')
		    ->where('s.indexbatiment = ? ', $this->getPrimaryKey());

		 return $q->execute();
	}

	public function getSecondOeuvres()
	{
		$q = Doctrine_Query::create()
		    ->from('SecondOeuvre se')
		    ->leftJoin('se.BibSo bs')
		    ->leftJoin('bs.BibTypeSo bts')
		    ->leftJoin('se.BibConservation bc')
		    ->where('se.indexbatiment = ? ', $this->getPrimaryKey());

		 return $q->execute();
	}

	public function getEquipementss()
	{
		$q = Doctrine_Query::create()
		    ->from('Equipements e')
		    ->leftJoin('e.BibEquipement be')
		    ->leftJoin('be.BibTypeEquipement bte')
		    ->leftJoin('e.BibConservation bc')
		    ->where('e.indexbatiment = ? ', $this->getPrimaryKey());

		 return $q->execute();
	}

	public function getElementsPaysagerss()
	{
		$q = Doctrine_Query::create()
		    ->from('ElementsPaysagers ep')
		    ->leftJoin('ep.BibElementPaysager bep')
		    ->leftJoin('ep.BibConservation bc')
		    ->where('ep.indexbatiment = ? ', $this->getPrimaryKey());

		 return $q->execute();
	}

	public function getIllustrations()
	{
		$q = Doctrine_Query::create()
		    ->from('Illustration i')
		    ->leftJoin('i.BibIllustration bi')
		    ->leftJoin('i.BibPersonnes bp')
		    ->where('i.indexbatiment = ? ', $this->getPrimaryKey());

		 return $q->execute();
	}

	public function getEnquetess()
	{
		$q = Doctrine_Query::create()
		    ->from('Enquetes e')
		    ->leftJoin('e.BibPersonnes bp')
		    ->where('e.indexbatiment = ? ', $this->getPrimaryKey());

		 return $q->execute();
	}
}