<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IdentificationTable extends Doctrine_Table
{
	public static function addFilterQuery($filters, $query, $rootAlias)
	{
		// exclure les batt avec le flag bat_suppr
		$query->addWhere($query->getRootAlias().'.bat_suppr = false');
		
		if (isset($filters['codesecteur']))
		{
			$query
				->leftJoin($rootAlias.'.BibCommune bc')
				->leftJoin('bc.BibSecteur bs')
				->addWhere('bs.codesecteur = '.$filters['codesecteur']);
		}

		if (isset($filters['codematge_spv']))
		{
			$query
				->leftJoin($rootAlias.'.Structuress s1 ON ' . $rootAlias . '.indexbatiment = s1.indexbatiment AND s1.codestructure = 2')
				->addWhere('s1.codematge = ?', $filters['codematge_spv']);
		}

		if (isset($filters['codematge_ch']))
		{
			$query
				->leftJoin($rootAlias.'.Structuress s2 ON ' . $rootAlias . '.indexbatiment = s2.indexbatiment AND s2.codestructure = 4')
				->addWhere('s2.codematge = ?', $filters['codematge_ch']);
		}

		if (isset($filters['codematge_co']))
		{
			$query
				->leftJoin($rootAlias.'.Structuress s3 ON ' . $rootAlias . '.indexbatiment = s3.indexbatiment AND s3.codestructure = 5')
				->addWhere('s3.codematge = ?', $filters['codematge_co']);
		}

		if (isset($filters['codeequipement']))
		{
			$query
				->leftJoin($rootAlias.'.Equipementss e')
				->addWhere('e.codeequipement = ?', $filters['codeequipement']);
		}

		if (isset($filters['codeperspective']))
		{
			$query
				->leftJoin($rootAlias.'.RelIdentPerspectives rip')
				->addWhere('rip.codeperspective = ?', $filters['codeperspective']);
		}

//		if (isset($filters['filters__identification__name']))
//		{
//			$query->addWhere($query->getRootAlias() . '.appelation ILIKE ?', '%' . $filters['filters__identification__name'] . '%');
//		}
		
		if (isset($filters['name']))
		{
			$query->addWhere($query->getRootAlias() . '.appelation ILIKE ?', '%' . $filters['name'] . '%');
		}

		return $query;
	}
}