<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IllustrationTable extends Doctrine_Table
{
	public static function sortByOrdreIllustration($query)
	{		
		$query->innerJoin('r.BibIllustration b');
		$query->orderBy('b.ordre_illustration');

		return $query;
	}
}