<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SecondOeuvre extends BaseSecondOeuvre
{
	public function getMatFinsAndFinitions()
	{
		$results = array();
		$i = 0;
		foreach ($this->getRelSoMatfins() as $rel)
		{
			$results['codematfins__'.$i] = $rel->getCodematfins();
			$results['codefinition__'.$i] = $rel->getCodefinition();
			$i++;
		}

		return $results;
	}

	public function getObjectMatFinsAndFinitions()
	{
		$results = array();
		$i = 0;



		return Doctrine_Query::create()
			->select('rsm.*')
		    ->from('RelSoMatfins rsm')
		    ->innerJoin('rsm.BibFinition bf')
		    ->innerJoin('rsm.Codematf bmf')
		    ->where('rsm.indexso = ?', $this->getIndexso())
		    ->execute();
	}

	public function getCodetypeso()
	{
		return $this->getBibSo()->getBibTypeSo()->getCodetypeso();
	}
}