<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Structures extends BaseStructures
{
	public function getMatFinsAndFinitions()
	{
		$results = array();
		$i = 0;
		foreach ($this->getRelStructuresMatfins() as $rel)
		{
			$results['codematfins__'.$i] = $rel->getCodematfins();
			$results['codefinition__'.$i] = $rel->getCodefinition();
			$i++;
		}

		return $results;
	}

	public function getObjectMatFinsAndFinitions()
	{
		$results = array();
		$i = 0;

		return Doctrine_Query::create()
			->select('rsm.*')
		    ->from('RelStructuresMatfins rsm')
		    ->leftJoin('rsm.BibFinition bf')
		    ->leftJoin('rsm.BibMateriauxFins bmf')
		    ->where('rsm.indexstructure = ?', $this->getIndexstructure())
		    ->execute();
	}
}