<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserCredentialTable extends Doctrine_Table
{
	public static function getCredentials($id_droit)
	{
		switch($id_droit)
		{
			// reader
			case 1:
				$credentials = null;
			break;
			
			// writer
			case 2:
				$credentials = array('save');
			break;
			
			// admin
			case 6:
				$credentials = array('save', 'admin');
			break;
			default:
				sfContext::getInstance()->getUser()->signOut();
			break;
		};
		
		return $credentials;
	}
}