generator:
  class: sfMmwExtjsDoctrineGenerator
  param:
    model_class:           BibTypeEquipement
    theme:                 mmwExtjs
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          bib_type_equipement
    with_doctrine_route:     1

    config:
      actions: ~
      fields:  ~
      list:
        display_field: type_equip
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
