<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardUserTable extends PluginsfGuardUserTable
{
	public static function importRoleTosfGuardUser()
	{
		$t_roles = Doctrine_Query::create()
			->from('TRoles')
			->execute();

		self::clearsfGuardUserTable();

		foreach($t_roles as $role)
		{
			if($role->getIdentifiant())
			{
				$user = new sfGuardUser();
				$user->setUsername($role->getIdentifiant());
				$user->setPassword($role->getPass());
				$user->setIsActive(true);
				$user->setAlgorithm('md5');
				$user->setRoleId($role->getIdRole());
				$user->save();
			}
		}

		//self::addTestUser();
	}

	public static function clearsfGuardUserTable()
	{
		$t_roles = Doctrine_Query::create()
			->delete('sfGuardUser')
			->execute();
	}

	public static function addTestUser()
	{
		$user = new TRoles();
		$user->setUsername('marco');
		$user->setPassword('5f4dcc3b5aa765d61d8327deb882cf99');
		$user->setIsActive(true);
		$user->setAlgorithm('md5');
		$user->save();
	}
}