<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardUser extends PluginsfGuardUser
{

	public function setTableDefinition()
    {
        parent::setTableDefinition(); 

        // add the role_id to the model
        $this->hasColumn('role_id', 'integer', 4, array('type' => 'integer', 'length' => '4'));

        $this->index('is_active_idx', array('fields' => array(0 => 'is_active')));
    }

	public function setPassword($password)
	{
		if (!$password && 0 == strlen($password))
		{
			return;
		}

		parent::_set('password', $password);
	}
}