<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2015/07/21 10:46:15

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'pgsql:host=localhost;dbname=appli_patrimoine_bati',
  'username' => 'cartopne',
  'password' => 'superpg',
  'phptype' => 'pgsql',
  'name' => 'doctrine',
)),);
