<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2015/07/21 10:46:15
sfConfig::add(array(
  'app_sf_combine_filter_plugin_css_filtered_paths' => array (
  0 => '/var/www/localhost/private/trunk/patrimoine_bati',
  1 => 'plugins/',
  2 => 'web/',
),
  'app_sf_combine_filter_plugin_js_exclude_files' => array (
  0 => '/js/mmwExtjs/modules/helper.js',
  1 => 'jquery-prototype-fix',
  2 => 'prototype',
  3 => 'effects',
  4 => 'builder',
  5 => 'dragdrop',
  6 => 'controls',
),
  'app_sf_combine_filter_plugin_javascripts' => false,
  'app_sf_combine_filter_plugin_stylesheets' => false,
  'app_sf_combine_filter_plugin_minimize_js' => true,
  'app_sf_combine_filter_plugin_minimize_css' => true,
  'app_sf_combine_filter_plugin_enabled' => true,
  'app_images_upload_dir' => 'uploads/images/',
  'app_document_upload_dir' => 'uploads/documents/',
  'app_sf_guard_plugin_success_signin_url' => '@homepage',
));
