<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2015/07/21 10:46:16
sfConfig::add(array(
  'mod_'.strtolower($moduleName).'_enabled' => true,
  'mod_'.strtolower($moduleName).'_view_class' => 'sfPHP',
  'mod_'.strtolower($moduleName).'_is_internal' => false,
));
