<?php
// auto-generated by sfSecurityConfigHandler
// date: 2015/07/21 10:46:15
$this->security = array (
  'sfguarduser' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 'super_admin',
    ),
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
