generator:
  class: sfMmwExtjsDoctrineGenerator
  param:
    model_class:           RelStructuresMatfins
    theme:                 mmwExtjs
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          rel_structures_matfins
    with_doctrine_route:     1

    config:
      actions: ~
      fields:  ~
      list:    ~
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
