generator:
  class: sfMmwExtjsDoctrineGenerator
  param:
    model_class:           RelMasque
    theme:                 mmwExtjs
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          rel_masque
    with_doctrine_route:     1

    config:
      actions: ~
      fields:  ~
      list:
        title: "Liste des masques"
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
